//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connection
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ReportMisConduct
    {
        public int idReportMisConduct { get; set; }
        public string typeReport { get; set; }
        public System.DateTime dateHour { get; set; }
        public string additionalContext { get; set; }
        public string idReportedPlayer { get; set; }
        public string idReportingPlayer { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
